[Interface]
MTU = 1280
PostUp = iptables -t mangle -A OUTPUT -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1220
PostUp = iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1220
PostDown = iptables -t mangle -D OUTPUT -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1220 || true
PostDown = iptables -t mangle -D POSTROUTING -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1220 || true
PrivateKey = b7+slCvjWeFMy3yZWw7ZWIm1yzoHPMeDsNhNJhexbpM=
Address = 10.5.0.2/16
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = 3ZNjosvvIqfvu3/BqaLzNNXs9zWO4jXpcXNOmDMDpX0=
AllowedIPs = 0.0.0.0/0
Endpoint = berlin.de.wg.nordhold.net:51820
PersistentKeepalive = 25
