[Interface]
PostUp = ip route replace 195.16.73.81/32 via $(ip route show default 0.0.0.0/0 dev eth0 | awk '{print $3}') dev eth0
PostUp = ip route replace 193.200.221.48/32 via $(ip route show default 0.0.0.0/0 dev eth0 | awk '{print $3}') dev eth0
PostUp = ip route replace 185.181.60.212/32 via $(ip route show default 0.0.0.0/0 dev eth0 | awk '{print $3}') dev eth0
PrivateKey = CKViPr1xyHAezf6mqbke2qMMpxdrJk2JDtty1/4ngHM=
Address = 10.2.0.2/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = wpfRQRhJirL++QclFH6SDhc+TuJJB4UxbCABy7A1tS4=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 79.127.186.193:51820
PersistentKeepalive = 25
